# fly.toml
app = "basex"  # Replace with your desired Fly.io app name

[build]
  image = "whitecod/fastapi-book-project"  # Replace with your Docker image name

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1