# fly.toml
app = "basex"

[build]
image = "whitecod/fastapi-book-project"

[http_service]
auto_start_machines = true
auto_stop_machines = false  # Prevent Fly.io from stopping the machine
force_https = true
internal_port = 8000
min_machines_running = 1  # Keep at least 1 machine running
